---
"$schema": https://github.com/hyperledger-labs/fablo/releases/download/2.1.0/schema.json
global:
  fabricVersion: 2.5.11
  tls: false
  fabloRest: true
  peerDb: couchdb
  tools:
    explorer: true
orgs:
  - organization:
      name: Orderer
      domain: root.com
    orderers:
      - groupName: group1
        prefix: orderer
        type: solo
        instances: 1 
  - organization:
      name: police
      domain: police.example.com
    peer:
      instances: 1
      anchorPeer: peer0
      db: "CouchDb"
    tools:
      fabloRest: true
  - organization:
      name: judiciary
      domain: judiciary.example.com
    peer:
      instances: 1
      anchorPeer: peer0
      db: "CouchDb"
    tools:
      fabloRest: true
  - organization:
      name: forensic
      domain: forensic.example.com
    peer:
      instances: 1
      anchorPeer: peer0
      db: "CouchDb"
    tools:
      fabloRest: true
channels:
  - name: ch1
    orgs:
      - name: police
        peers:
          - peer0
      - name: judiciary
        peers:
          - peer0
      - name: forensic
        peers:
          - peer0
  - name: ch2
    orgs:
      - name: judiciary
        peers:
          - peer0
      - name: forensic
        peers:
          - peer0
  - name: ch3
    orgs:
      - name: police
        peers:
          - peer0
chaincodes:
  - name: addevidence-ch1
    version: "1.0"
    lang: golang
    channel: ch1
    directory: ./chaincode/addevidence
    endorsement: "OR('policeMSP.member', 'forensicMSP.member')"


  - name: addevidence-ch2
    version: "1.0"
    lang: golang
    channel: ch2
    directory: ./chaincode/addevidence
    endorsement: "OR('policeMSP.member', 'forensicMSP.member')"
 
  - name: addevidence-ch3
    version: "1.0"
    lang: golang
    channel: ch3
    directory: ./chaincode/addevidence
    endorsement: "OR('policeMSP.member', 'judiciaryMSP.member', 'forensicMSP.member')"
