---
"$schema": https://github.com/hyperledger-labs/fablo/releases/download/2.1.0/schema.json
global:
  fabricVersion: 2.5.11
  tls: false
  fabloRest: true
  tools:
    explorer: true
orgs:
  - organization:
      name: Orderer
      domain: root.com
    orderers:
      - groupName: group1
        prefix: orderer
        type: solo
        instances: 1 
  - organization:
      name: police
      domain: police.example.com
    peer:
      instances: 1
      db: CouchDb
  - organization:
      name: judiciary
      domain: judiciary.example.com
    peer:
      instances: 1
      db: CouchDb
  - organization:
      name: forensic
      domain: forensic.example.com
    peer:
      instances: 1
      db: CouchDb
channels:
  - name: ch1
    orgs:
      - name: police
        peers:
          - peer0
          - peer1
      - name: judiciary
        peers:
          - peer0
          - peer1
      - name: forensic
        peers:
          - peer0
          - peer1
  - name: ch2
    orgs:
      - name: judiciary
        peers:
          - peer0
          - peer1
      - name: forensic
        peers:
          - peer0
          - peer1
  - name: ch4
    orgs:
      - name: police
        peers:
          - peer0
          - peer1
chaincodes:
  - name: addevidence-ch1
    version: "1.0"
    lang: golang
    channel: ch1
    directory: ./chaincode/theliv
    endorsement: "AND('policeMSP.member', 'forensicMSP.member', 'judiciaryMSP.member')"


  - name: addevidence-ch2
    version: "1.0"
    lang: golang
    channel: ch2
    directory: ./chaincode/theliv
    endorsement: "AND('judiciaryMSP.member', 'forensicMSP.member')"
    
  - name: addevidence-ch2
    version: "1.0"
    lang: golang
    channel: ch2
    directory: ./chaincode/theliv
    endorsement: "AND('policeMSP.member')"


  - name: retrieveevidence-ch1
    version: "1.0"
    lang: golang
    channel: ch1
    directory: ./chaincode/theliv
    endorsement: "OR('policeMSP.member', 'judiciaryMSP.member', 'forensicMSP.member')"
  
  - name: retrieveevidence-ch2
    version: "1.0"
    lang: golang
    channel: ch2
    directory: ./chaincode/theliv
    endorsement: "OR('policeMSP.member', 'judiciaryMSP.member', 'forensicMSP.member')"
 
  - name: retrieveevidence-ch3
    version: "1.0"
    lang: golang
    channel: ch3
    directory: ./chaincode/theliv
    endorsement: "OR('policeMSP.member', 'judiciaryMSP.member', 'forensicMSP.member')"
  
  - name: transfer-ch1
    version: "1.0"
    lang: golang
    channel: ch1
    directory: ./chaincode/theliv
    endorsement: "AND('policeMSP.member', 'judiciaryMSP.member')"

  - name: transfer-ch2
    version: "1.0"
    lang: golang
    channel: ch2
    directory: ./chaincode/theliv
    endorsement: "AND('policeMSP.member', 'judiciaryMSP.member')"


  - name: audit-ch1
    version: "1.0"
    lang: golang
    channel: ch1
    directory: ./chaincode/theliv
    endorsement: "MAJORITY('policeMSP.member', 'forensicMSP.member', 'judiciaryMSP.member')"
  
  - name: audit-ch2
    version: "1.0"
    lang: golang
    channel: ch2
    directory: ./chaincode/theliv
    endorsement: "MAJORITY('policeMSP.member', 'forensicMSP.member', 'judiciaryMSP.member')"
   
  - name: audit-ch3
    version: "1.0"
    lang: golang
    channel: ch3
    directory: ./chaincode/theliv
    endorsement: "MAJORITY('policeMSP.member', 'forensicMSP.member', 'judiciaryMSP.member')"
