# Generated by Django 5.1.7 on 2025-03-20 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='evd_title',
            new_name='evd_name',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='submitted_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='evd_id',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='evidence',
            name='added_by_django',
            field=models.CharField(default=datetime.datetime(2025, 3, 20, 8, 56, 14, 990936, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='custom_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
