# Generated by Django 5.1.7 on 2025-03-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_rename_evd_title_evidence_evd_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
