# Generated by Django 5.1.7 on 2025-03-26 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_alter_evidence_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
